version: "3.8"
services:

  proxy:
    container_name: proxy
    build: ./
    ports:
      - 10000:10000
    environment:
      AUTH_URL: 'http://auth:3000'
      CUSTOMER_URL: 'http://customers:4000'
      ACCOUNTS_URL: 'http://accounts:5000'

  auth:
    container_name: auth
    build: ./auth
    ports:
      - 3000:3000

  customers:
    container_name: customers
    build: ./customers
    ports:
      - 4000:4000
    depends_on:
      - customers_db
    environment:
      - MYSQL_HOST=customer_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  customers_db:
    image: mysql
    container_name: customers_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  accounts:
    build: ./accounts
    ports:
      - "5000:5000"
    depends_on:
      - accounts_db
    environment:
      - MYSQL_HOST=accounts_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  accounts_db:
    image: mysql
    container_name: accounts_db
    environment:
      MYSQL_ROOT_PASSWORD: password
  # order:
  #   build: ./order
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #     - book
  #     - customer
  # wallet:
  #   build: ./wallet
  #   ports:
  #     - "6000:6000"
  #   depends_on:
  #     - mongo
  #     - book
  #     - customer