version: "3.8"
services:

  proxy:
    container_name: proxy
    build: ./
    ports:
      - 10000:10000
    depends_on:
      - auth
      - customers
      - accounts
      - stocks
      - wallets
      - customers_db
      - accounts_db
      - stocks_db
      - wallets_db
    environment:
      AUTH_URL: 'http://auth:3100'
      CUSTOMER_URL: 'http://customers:4100'
      ACCOUNTS_URL: 'http://accounts:5100'
      ORDERS_URL: 'http://orders:6100'
      STOCKS_URL: 'http://stocks:7100'
      WALLETS_URL: 'http://stocks:8100'

  auth:
    container_name: auth
    build: ./auth
    ports:
      - 3100:3100

  customers:
    container_name: customers
    build: ./customers
    ports:
      - 4100:4100
    depends_on:
      - customers_db
    environment:
      - MYSQL_HOST=customers_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  accounts:
    build: ./accounts
    ports:
      - 5100:5100
    depends_on:
      - accounts_db
    environment:
      - MYSQL_HOST=accounts_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
  
  orders:
    container_name: orders
    build: ./orders
    ports:
      - 6100:6100
    depends_on:
      - orders_db
    environment:
      - MYSQL_HOST=orders_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  stocks:
    container_name: stocks
    build: ./stocks
    ports:
      - 7100:7100
    depends_on:
      - stocks_db
    environment:
      - MYSQL_HOST=stocks_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  wallets:
    container_name: wallets
    build: ./wallets
    ports:
      - 8100:8100
    depends_on:
      - wallets_db
    environment:
      - MYSQL_HOST=wallets_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

 
  customers_db:
    image: mysql
    container_name: customers_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  accounts_db:
    image: mysql
    container_name: accounts_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  stocks_db:
    image: mysql
    container_name: stocks_db
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  wallets_db:
    image: mysql
    container_name: wallets_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  orders_db:
    image: mysql
    container_name: orders_db
    environment:
      MYSQL_ROOT_PASSWORD: password
