version: "3.8"
services:

  proxy:
    container_name: proxy
    build: ./
    ports:
      - 10000:10000
    depends_on:
      - auth
      - customers
      - accounts
      - stocks
      - customers_db
      - accounts_db
    environment:
      AUTH_URL: 'http://auth:3100'
      CUSTOMER_URL: 'http://customers:4100'
      ACCOUNTS_URL: 'http://accounts:5100'
      STOCKS_URL: 'http://stocks:7100'

  auth:
    container_name: auth
    build: ./auth
    ports:
      - 3100:3100

  stocks:
    container_name: stocks
    build: ./stocks
    ports:
      - 7100:7100
    depends_on:
      - stocks_db
    environment:
      - MYSQL_HOST=stocks_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    

  customers:
    container_name: customers
    build: ./customers
    ports:
      - 4100:4100
    depends_on:
      - customers_db
    environment:
      - MYSQL_HOST=customers_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  accounts:
    build: ./accounts
    ports:
      - 5100:5100
    depends_on:
      - accounts_db
    environment:
      - MYSQL_HOST=accounts_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  customers_db:
    image: mysql
    container_name: customers_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  accounts_db:
    image: mysql
    container_name: accounts_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  stocks_db:
    image: mysql
    container_name: stocks_db
    environment:
      MYSQL_ROOT_PASSWORD: password
  # order:
  #   build: ./order
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #     - book
  #     - customer
  # wallet:
  #   build: ./wallet
  #   ports:
  #     - "6000:6000"
  #   depends_on:
  #     - mongo
  #     - book
  #     - customer