DROP SCHEMA IF EXISTS Stocks_db;
CREATE SCHEMA IF NOT EXISTS Stocks_db;
CREATE TABLE  Stocks_db.Stocks (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ticker VARCHAR(10) NOT NULL UNIQUE,
  price decimal(19,4) NOT NULL,
  availableQty int NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);